from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
)
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import matplotlib.pyplot as plt
import pandas as pd
from services.csv_service import load_dataframe
from services.ai_service import answer_question_local
from services.ml_service import detect_anomalies, generate_forecast
import base64
import tempfile
import os

def generate_executive_report(file_id: str, title: str = "Dataset Analysis") -> bytes:
    """Generate a full PDF report and return bytes."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=50, leftMargin=50,
        topMargin=60, bottomMargin=50,
        title=title
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='CenterHeading', parent=styles['Heading1'], alignment=TA_CENTER, fontSize=24, spaceAfter=20))
    styles.add(ParagraphStyle(name='SubHeading', parent=styles['Heading2'], fontSize=16, spaceAfter=12))
    styles.add(ParagraphStyle(name='BodyText2', parent=styles['Normal'], fontSize=11, leading=16, spaceAfter=10))

    story = []

    # Load data
    df = load_dataframe(file_id)
    columns = df.columns.tolist()
    num_rows = len(df)

    # Title page
    story.append(Paragraph(f"Executive Report: {title}", styles['CenterHeading']))
    story.append(Spacer(1, 0.2*inch))
    story.append(Paragraph(f"Generated by Deploytual", styles['Normal']))
    story.append(Spacer(1, 1*inch))

    # Executive summary (AI)
    summary_question = (
        "Provide a concise executive summary of this dataset. "
        "Include: what the data contains, key metrics, overall trends, and one actionable insight."
    )
    try:
        summary_result = answer_question_local(file_id, summary_question)
        summary_text = summary_result.get("answer", "No summary available.")
    except:
        summary_text = "AI summary could not be generated."

    story.append(Paragraph("1. Executive Summary", styles['SubHeading']))
    story.append(Paragraph(summary_text, styles['BodyText2']))
    story.append(Spacer(1, 0.3*inch))

    # Data overview
    story.append(Paragraph("2. Data Overview", styles['SubHeading']))
    overview = f"<b>File ID:</b> {file_id}<br/>"
    overview += f"<b>Rows:</b> {num_rows}<br/>"
    overview += f"<b>Columns:</b> {len(columns)}<br/>"
    overview += f"<b>Column Names:</b> {', '.join(columns[:15])}{'...' if len(columns) > 15 else ''}"
    story.append(Paragraph(overview, styles['BodyText2']))
    story.append(Spacer(1, 0.2*inch))

    # Schema
    story.append(Paragraph("3. Schema", styles['SubHeading']))
    schema_data = [["Column Name", "Type"]]
    for col in columns:
        dtype = str(df[col].dtype)
        schema_data.append([col, dtype])
    t = Table(schema_data, colWidths=[2.5*inch, 2.5*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#2563eb")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 10),
        ('BOTTOMPADDING', (0,0), (-1,0), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8faff")])
    ]))
    story.append(t)
    story.append(Spacer(1, 0.2*inch))

    # Statistical summary
    story.append(Paragraph("4. Statistical Summary", styles['SubHeading']))
    try:
        desc = df.describe(include='all').transpose().reset_index()
        desc_data = [desc.columns.tolist()] + desc.values.tolist()
        t2 = Table(desc_data, colWidths=[1.8*inch] + [1.2*inch]*(len(desc_data[0])-1))
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#2563eb")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 8),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8faff")]),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(t2)
    except Exception:
        story.append(Paragraph("Could not compute statistical summary.", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))

    # Anomaly detection
    story.append(Paragraph("5. Anomaly Detection", styles['SubHeading']))
    try:
        anomalies = detect_anomalies(file_id)
        if "error" not in anomalies:
            anomaly_text = f"Anomalies detected: {anomalies['anomalies_count']} out of {anomalies['total_rows']} rows."
            story.append(Paragraph(anomaly_text, styles['BodyText2']))
            if anomalies.get('anomaly_sample'):
                anom_data = [list(anomalies['anomaly_sample'][0].keys())]
                for row in anomalies['anomaly_sample']:
                    anom_data.append([str(row.get(k,'')) for k in anom_data[0]])
                t_anom = Table(anom_data, colWidths=[1.5*inch]*len(anom_data[0]))
                t_anom.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#dc2626")),
                    ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                    ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
                    ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#fee2e2")]),
                    ('FONTSIZE', (0,0), (-1,-1), 8),
                ]))
                story.append(t_anom)
        else:
            story.append(Paragraph(f"Anomaly detection error: {anomalies['error']}", styles['Normal']))
    except Exception as e:
        story.append(Paragraph(f"Anomaly detection failed: {e}", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))

    # Forecasting (if date column exists)
    date_col = None
    for col in columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            date_col = col
            break
    if date_col is None:
        for col in columns:
            try:
                pd.to_datetime(df[col])
                date_col = col
                break
            except:
                pass

    if date_col:
        numeric_cols = df.select_dtypes(include='number').columns.tolist()
        if numeric_cols:
            target = numeric_cols[0]
            story.append(Paragraph("6. Time‑Series Forecast", styles['SubHeading']))
            try:
                forecast_res = generate_forecast(file_id, date_col, target, periods=12)
                if 'forecast_plot' in forecast_res:
                    img_data = base64.b64decode(forecast_res['forecast_plot'].split(',')[1])
                    with tempfile.NamedTemporaryFile(delete=False, suffix='.png') as tmp:
                        tmp.write(img_data)
                        tmp_path = tmp.name
                    img = Image(tmp_path, width=5*inch, height=3*inch)
                    story.append(img)
                    os.unlink(tmp_path)
                if forecast_res.get('future_predictions'):
                    pred_data = [list(forecast_res['future_predictions'][0].keys())]
                    for row in forecast_res['future_predictions']:
                        pred_data.append([str(row.get(k,'')) for k in pred_data[0]])
                    t_pred = Table(pred_data, colWidths=[1.5*inch]*len(pred_data[0]))
                    t_pred.setStyle(TableStyle([
                        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#2563eb")),
                        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
                        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8faff")]),
                        ('FONTSIZE', (0,0), (-1,-1), 8),
                    ]))
                    story.append(t_pred)
            except Exception as e:
                story.append(Paragraph(f"Forecast generation failed: {e}", styles['Normal']))
    else:
        story.append(Paragraph("6. Forecasting: No date column detected.", styles['SubHeading']))
    story.append(Spacer(1, 0.2*inch))

    # Suggested follow-up questions
    story.append(Paragraph("7. Suggested Next Questions", styles['SubHeading']))
    suggestions = answer_question_local(file_id, "Suggest 3 follow-up analysis questions.").get("suggested_followups", [])
    for i, q in enumerate(suggestions, 1):
        story.append(Paragraph(f"{i}. {q}", styles['BodyText2']))

    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
