apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploytual.fullname" . }}-backend
  labels:
    {{- include "deploytual.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "deploytual.selectorLabels" . | nindent 4 }}
    tier: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
