apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deploytual.fullname" . }}-backend
  labels:
    {{- include "deploytual.labels" . | nindent 4 }}
    tier: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deploytual.selectorLabels" . | nindent 6 }}
      tier: backend
  template:
    metadata:
      labels:
        {{- include "deploytual.selectorLabels" . | nindent 8 }}
        tier: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "deploytual.fullname" . }}-secrets
                  key: google-client-id
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "deploytual.fullname" . }}-secrets
                  key: secret-key
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
