{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deploytual.fullname" . }}-frontend
  labels:
    {{- include "deploytual.labels" . | nindent 4 }}
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "deploytual.selectorLabels" . | nindent 6 }}
      tier: frontend
  template:
    metadata:
      labels:
        {{- include "deploytual.selectorLabels" . | nindent 8 }}
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: {{ .Values.frontend.configMapName }}
{{- end }}
